### ISSUE TITLE
NPM DataTables cannot display more than 10 columns

### ISSUE THREAD

**Issue by katrina-engelbrecht** [DataTables/DataTables#917]
If datatable has more than 10 columns, Angular2 throws exception: 
`EXCEPTION: Uncaught (in promise): Error: Unsupported number of argument for pure functions: 11
Error: Unsupported number of argument for pure functions: 11
    at createPureProxy (http://localhost:4201/js/vendor.bundle.js:10955:15) [angular]
    at createCachedLiteralArray (http://localhost:4201/js/vendor.bundle.js:20200:101) [angular]
    at _AstToIrVisitor.visitLiteralArray (http://localhost:4201/js/vendor.bundle.js:19681:139) [angular]
    at LiteralArray.visit (http://localhost:4201/js/vendor.bundle.js:49480:24) [angular]
    at _AstToIrVisitor.visit (http://localhost:4201/js/vendor.bundle.js:19828:48) [angular]
    at _AstToIrVisitor.visitLiteralMap (http://localhost:4201/js/vendor.bundle.js:19692:43) [angular]
    at LiteralMap.visit (http://localhost:4201/js/vendor.bundle.js:49507:24) [angular]
    at ASTWithSource.visit (http://localhost:4201/js/vendor.bundle.js:49721:25) [angular]
    at convertPropertyBinding (http://localhost:4201/js/vendor.bundle.js:19346:50) [angular]
    at http://localhost:4201/js/vendor.bundle.js:96166:165 [angular]
    at Array.forEach (native) [angular]
    at bindDirectiveInputs (http://localhost:4201/js/vendor.bundle.js:96162:25) [angular]
    at http://localhost:4201/js/vendor.bundle.js:96341:113 [angular]
    at Array.forEach (native) [angular]
    at ViewBinderVisitor.visitElement (http://localhost:4201/js/vendor.bundle.js:96339:24) [angular]
    at ElementAst.visit (http://localhost:4201/js/vendor.bundle.js:11376:24) [angular]
    at visit (http://localhost:4201/js/vendor.bundle.js:11657:37) [angular]
    at http://localhost:4201/js/vendor.bundle.js:11659:42 [angular]
    at Array.forEach (native) [angular]
    at templateVisitAll (http://localhost:4201/js/vendor.bundle.js:11658:10) [angular]
    at ViewBinderVisitor.visitElement (http://localhost:4201/js/vendor.bundle.js:96344:119) [angular]
    at ElementAst.visit (http://localhost:4201/js/vendor.bundle.js:11376:24) [angular]
    at visit (http://localhost:4201/js/vendor.bundle.js:11657:37) [angular]
    at http://localhost:4201/js/vendor.bundle.js:11659:42 [angular]
    at Array.forEach (native) [angular]
    at templateVisitAll (http://localhost:4201/js/vendor.bundle.js:11658:10) [angular]
    at ViewBinderVisitor.visitElement (http://localhost:4201/js/vendor.bundle.js:96344:119) [angular]
    at ElementAst.visit (http://localhost:4201/js/vendor.bundle.js:11376:24) [angular]
    at visit (http://localhost:4201/js/vendor.bundle.js:11657:37) [angular]
    at http://localhost:4201/js/vendor.bundle.js:11659:42 [angular]
    at Array.forEach (native) [angular]
    at templateVisitAll (http://localhost:4201/js/vendor.bundle.js:11658:10) [angular]
    at ViewBinderVisitor.visitElement (http://localhost:4201/js/vendor.bundle.js:96344:119) [angular]
    at ElementAst.visit (http://localhost:4201/js/vendor.bundle.js:11376:24) [angular]
    at visit (http://localhost:4201/js/vendor.bundle.js:11657:37) [angular]
    at http://localhost:4201/js/vendor.bundle.js:11659:42 [angular]
    at Array.forEach (native) [angular]
    at templateVisitAll (http://localhost:4201/js/vendor.bundle.js:11658:10) [angular]
    at ViewBinderVisitor.visitElement (http://localhost:4201/js/vendor.bundle.js:96344:119) [angular]
    at ElementAst.visit (http://localhost:4201/js/vendor.bundle.js:11376:24) [angular]
    at visit (http://localhost:4201/js/vendor.bundle.js:11657:37) [angular]
    at http://localhost:4201/js/vendor.bundle.js:11659:42 [angular]
    at Array.forEach (native) [angular]
    at templateVisitAll (http://localhost:4201/js/vendor.bundle.js:11658:10) [angular]
    at ViewBinderVisitor.visitElement (http://localhost:4201/js/vendor.bundle.js:96344:119) [angular]
    at ElementAst.visit (http://localhost:4201/js/vendor.bundle.js:11376:24) [angular]
    at visit (http://localhost:4201/js/vendor.bundle.js:11657:37) [angular]
    at http://localhost:4201/js/vendor.bundle.js:11659:42 [angular]
    at Array.forEach (native) [angular]
    at templateVisitAll (http://localhost:4201/js/vendor.bundle.js:11658:10) [angular]
    at ViewBinderVisitor.visitElement (http://localhost:4201/js/vendor.bundle.js:96344:119) [angular]
    at ElementAst.visit (http://localhost:4201/js/vendor.bundle.js:11376:24) [angular]
    at visit (http://localhost:4201/js/vendor.bundle.js:11657:37) [angular]
    at http://localhost:4201/js/vendor.bundle.js:11659:42 [angular]
    at Array.forEach (native) [angular]
    at templateVisitAll (http://localhost:4201/js/vendor.bundle.js:11658:10) [angular]
    at ViewBinderVisitor.visitElement (http://localhost:4201/js/vendor.bundle.js:96344:119) [angular]
    at ElementAst.visit (http://localhost:4201/js/vendor.bundle.js:11376:24) [angular]
    at visit (http://localhost:4201/js/vendor.bundle.js:11657:37) [angular]
    at http://localhost:4201/js/vendor.bundle.js:11659:42 [angular]
    at Array.forEach (native) [angular]
    at templateVisitAll (http://localhost:4201/js/vendor.bundle.js:11658:10) [angular]
    at bindView (http://localhost:4201/js/vendor.bundle.js:96290:115) [angular]
    at ViewCompiler.compileComponent (http://localhost:4201/js/vendor.bundle.js:23857:94) [angular]
    at JitCompiler._compileTemplate (http://localhost:4201/js/vendor.bundle.js:64410:65) [angular]
    at http://localhost:4201/js/vendor.bundle.js:64291:62 [angular]
    at Set.forEach (native) [angular]
    at JitCompiler._compileComponents (http://localhost:4201/js/vendor.bundle.js:64291:19) [angular]
    at createResult (http://localhost:4201/js/vendor.bundle.js:64173:19) [angular]
    at Object.onInvoke (http://localhost:4201/js/vendor.bundle.js:33229:37) [angular]
    at Zone.run (http://localhost:4201/js/polyfills.bundle.js:17291:43) [angular => angular]
    at http://localhost:4201/js/polyfills.bundle.js:17713:57 [angular]
    at Object.onInvokeTask (http://localhost:4201/js/vendor.bundle.js:33220:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:4201/js/polyfills.bundle.js:17452:40) [angular]
    at Zone.runTask (http://localhost:4201/js/polyfills.bundle.js:17329:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:4201/js/polyfills.bundle.js:17611:35) [<root>]`

**Comment by DataTables** [comment]
My apologies if the "New issue" template text isn't clear enough. Please post all support questions in the [DataTables forums](//datatables.net/forums) with a link to a test case showing the issue.

DataTables itself has no hard limit on the number of columns, but I haven't used any Angular integration for DataTables myself, so I can't really comment on that aspect of it. You might need to ask the author of whatever integration you are using.

**Comment by katrina-engelbrecht** [comment]
I use datatables NPM Package which is listed on your official website. https://datatables.net/download/npm 
which is used in https://smartadmin-ng2.github.io/#/tables/datatables and our company has bought its source codes. Just try to update any jquery datatables with more than 10 columns, it throws error like what I pasted in this issue.

**Comment by DataTables** [comment]
I'd suggest you ask the author of the SmartAdmin panel then. I am indeed the author of the DataTables library, but not of the SmartAdmin theme, and I do not currently provide any Angular integration for DataTables. Likewise I don't receive any royalties, commission or any other fees from SmartAdmin. If you paid for their software, its them you should speak to :-)

**Comment by katrina-engelbrecht** [comment]
But this NPM Package is your product. Or?
Regardless of smartadmin, try to make any html table with datatable NPM package in angular, by more than 10 columns it will throw exception. I don't think SmartAdmin should be responsible for this error.

**Comment by DataTables** [comment]
The NPM package is yes, but not the Angular aspect. I have no idea what a "pure function" is for example (first line in the error message).

DataTables places no hard limits on the number of columns - example with 20 columns: http://live.datatables.net/jopipuxu/1/edit

**Comment by katrina-engelbrecht** [comment]
Thanks for the information. I will hand over this issue to angular2 support forum.
